updates:
  check-for-updates: true
  show-admin: true
mysql:
  enabled: false
  username: 'root'
  password: 'root'
  database: 'database'
  host: 'localhost'
  port: 3306
  table-prefix: 'cq_'
arena:
  countdown: 30
  game-length: 450
  after-count: 15
  crystal-spawn-chance: 20
  item-spawn-chance: 100
  team-colour-prefix: true
  force-even-teams: true
  blood: true
  blood-material: redstone_block
  chat-silence: false
wand:
  regen-fire: 6 
  regen-teleport: 12
  regen-healing: 12
  regen-ice: 12
  regen-wither: 6
shop:
  start-price: 250
  multiplier: 1.75
  crystal-multiplier: 1
  crystal-message: '%teamcolour%+%amount% Crystal(s)'
rarity:
  crystal-shard: 1
  small-crystal: 1.5
  shiny-crystal: 2.5
  lightning-bolt: 2.5
  glue: 2.5
  landmine: 1
  wolf: 1
  creeper-egg: 1
  hammer: 1
  wither: 2.5
  shield: 1
  strength: 1
  flower: 1
  apple: 1
  railgun: 1.5
  blooper: 2.5
  speed: 1
  health: 1
  grenade: 1
  anvil: 1
  tnt: 1
  telepearl: 1
  bunny: 2
  bomb: 1
  curse: 2.5
  poison-dart: 1
  force-field: 1
  sugar: 1
  smart-bomb: 1
  totem-of-undying: 4
kit:
  default:
    name: '&dCrystal Hunter'
    icon: ender_eye
    lore: '&7&oThe default class%nl%&f&7&oUses sword and bow.'
    items:
      - team_helmet,1,[e unbreaking;10]
      - team_chestplate
      - team_leggings
      - team_boots
      - wooden_sword;Crystal Smasher,1,[e unbreaking;10]
      - bow,1,[e infinity;1;unbreaking;10]
      - arrow,1
  archer:
    name: '&aArcher'
    icon: bow
    lore: '&7&oRanged Blood'
    items:
      - team_helmet,1,[e unbreaking;10]
      - leather_chestplate
      - leather_leggings
      - leather_boots
      - bow,1,[e power;1;punch;1;infinity;1;sharpness;1]
      - arrow,1
  knight:
    name: '&7Knight'
    icon: stone_sword
    lore: '&7&oMedieval Madness'
    items:
      - chainmail_helmet
      - chainmail_chestplate
      - team_leggings,1,[e unbreaking;10]
      - chainmail_boots
      - stone_sword,1,[e unbreaking;10]
      - shield,1,[d 317]
  caveman:
    name: '&eCaveman'
    icon: bone
    lore: '&7&oThe way of the ancients%nl%%nl%&9Ability: &bStrength'
    ability:
      - strength
    items:
      - team_chestplate,1,[e unbreaking;10]
      - stick;Club,1,[e sharpness;6]
      - sugar_cane;&2Poison &aDart,4
  poseidon:
    name: '&9Poseidon'
    icon: trident
    lore: '&7&oThe god of the sea and other waters,%nl%&7&oearthquakes, and horses.%nl%%nl%&9Ability: &bWater Healing'
    ability:
      - water_healing
    items:
      - trident,1,[e loyalty;2;unbreaking;10]
      - team_leggings,1,[e protection;1;unbreaking;10]
      - team_boots,1,[e depth_strider;2;protection;1;unbreaking;10]
  fishtfight:
    name: '&bFishtFight'
    icon: cod
    lore: '&7&oFlippin Heck Mun!%nl%%nl%&9Ability: &bWater Healing'
    ability:
      - water_healing
    items:
      - team_helmet,1,[e unbreaking;10]
      - cod;&bWay too smelly fish,1,[e knockback;1]
  tnt:
    name: '&a&l&oPRO &4TNT'
    icon: tnt
    lore: '&7&oPoofs and booms.%nl%%nl%&9Ability: &bExplosive Arrows'
    ability:
      - explosive_arrows
    items:
      - wooden_sword,1,[e knockback;1;unbreaking;10]
      - bow,1
      - tnt,8
      - arrow;Flying Bombs,16
      - golden_helmet,1,[e blast_protection;2;unbreaking;10]
      - team_boots,1,[e blast_protection;2;unbreaking;10]
      - team_chestplate,1,[e blast_protection;2;unbreaking;10]
      - team_leggings,1,[e blast_protection;2;unbreaking;10]
  ranger:
    name: '&a&l&oPRO &2Ranger'
    icon: leather_chestplate
    lore: '&7&oChild of Mother Nature%nl%%nl%&9Ability: &bDouble-Jump Boost%nl%&9Ability:
      &bAgility'
    ability:
      - doublejump_boost
      - agility
    items:
      - team_helmet,1,[e protection;3;unbreaking;10]
      - leather_chestplate,1
      - leather_boots,1
      - leather_leggings,1
      - wooden_sword,1,[e unbreaking;10]
      - bow,1,[e infinity;1;punch;2;power;2;unbreaking;10]
      - arrow,1
      - bone;&fWolfie &c<3,3
  iron-golem:
    name: '&a&l&oPRO &6Iron Golem'
    icon: carved_pumpkin
    lore: '&7&oOnly the strongest will survive%nl%%nl%&9Ability: &bHealth Boost%nl%&9Weakness:
      &bWater'
    ability:
      - health_boost
      - corroding
    items:
      - team_helmet,1,[e unbreaking;10]
      - iron_chestplate,1,[e protection;1]
      - iron_leggings,1,[e protection;1]
      - team_boots,1,[e unbreaking;10]
      - iron_sword,1,[e unbreaking;10]
      - bow,1,[e infinity;1;unbreaking;10]
      - arrow,1
  priest:
    name: '&a&l&oPRO &aPriest'
    icon: blaze_rod
    lore: '&7&oBlesses to impress'
    items:
      - wand_healing,1,[e sharpness;3;unbreaking;10]
      - wand_ice,1,[e sharpness;3;unbreaking;10]
      - wand_ender,1,[e sharpness;3;unbreaking;10]
      - team_helmet,1,[e protection;2;unbreaking;10]
      - team_chestplate,1,[e protection;1;unbreaking;10]
      - team_leggings
      - team_boots
      - totem_of_undying
  fire-wizard:
    name: '&a&l&oPRO &cFire Wizard'
    icon: golden_hoe,1,[e sharpness;2]
    lore: '&7&oUses the magic of fire to slay their opponents%nl%%nl%&9Ability: &bLast Revenge%nl%&9Ability: &bFaster Recharge%nl%&9Weakness: &bWater'
    ability:
      - last_revenge
      - magical_aura
      - corroding
    items:
      - wand_fire,1,[e sharpness;2;unbreaking;10]
      - team_helmet,1,[e protection;2;fire_protection;2;unbreaking;10]
      - team_chestplate
      - team_leggings
      - team_boots
  voldemort:
    name: '&a&l&oPRO &2Voldemort'
    icon: stone_axe,1,[e sharpness;2]
    lore: '&7&oHe-Who-Must-Not-Be-Named%nl%&7&ocorrupts anyone within his reach%nl%%nl%&9Ability: &bDrain%nl%&9Ability: &bFaster Recharge'
    ability:
      - magical_aura
      - drain
    items:
      - wand_wither,1,[e unbreaking;10]
      - team_helmet,1,[e unbreaking;10]
      - team_chestplate
      - team_leggings
      - team_boots
  multi-wizard:
    name: '&a&l&oPRO &dMerlin'
    icon: diamond_hoe,1,[e sharpness;2]
    lore: '&7&oThe master of the magicians.%nl%&7&oUses all wands, but with longer recharge.%nl%%nl%&9Weakness: &bLonger Recharge'
    ability:
      - power_loss
    items:
      - wand_fire,1,[e sharpness;2;unbreaking;10]
      - wand_ender,1,[e sharpness;2;unbreaking;10]
      - wand_healing,1,[e sharpness;2;unbreaking;10]
      - wand_ice,1,[e sharpness;2;unbreaking;10]
      - wand_wither,1,[e unbreaking;10]
      - team_helmet,1,[e unbreaking;10]
      - team_chestplate
      - team_leggings
      - team_boots