name: CrystalQuest
main: nl.sugcube.crystalquest.CrystalQuest
version: 1.5
api-version: 1.14
authors: [SugarCaney]
website: www.twitter.com/CaneyDearie
softdepend: [Multiverse-Core]
description: >
             The battle for the crystals!
commands:
  cq:
    description: Main command of CrystalQuest-plugin.